// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'objectbox_entities_complete.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5467978026615599515),
    name: 'MessageEntity',
    lastPropertyId: const obx_int.IdUid(42, 5932748631482185153),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3770034241375713903),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2248947782106369079),
        name: 'messageId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 9180704768471713073),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3373707912520330813),
        name: 'senderId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 6128137228116313680),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1412011340755810765),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2119918857659501308),
        name: 'readAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 1724095004511227381),
        name: 'receiverId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(58, 2762996950371727183),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 6864901060075984937),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 4165629848885096432),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 5268428411898382567),
        name: 'isRead',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(59, 8347030690205368842),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 2316312455541842859),
        name: 'isDelivered',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(40, 3726549359848137933),
        name: 'isSent',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(41, 2542337145385933639),
        name: 'attachmentUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(42, 5932748631482185153),
        name: 'attachmentLocalPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1399498260393424036),
    name: 'PhotoEntity',
    lastPropertyId: const obx_int.IdUid(14, 2314365409751717571),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6562582849911528941),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5629970817789266956),
        name: 'photoId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(16, 4284453412325532584),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2552374184513372287),
        name: 'userId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(17, 623974254304267584),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4178087176773436485),
        name: 'localPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4527806955610173001),
        name: 'remotePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 74258813998320859),
        name: 'status',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(18, 8137819162317204723),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5652102618559000540),
        name: 'hasWatermark',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8849191550789706887),
        name: 'uploadedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6370112002516753636),
        name: 'moderatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6568229330521650249),
        name: 'moderatorId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1291879191982192012),
        name: 'rejectionReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4892388847827283425),
        name: 'displayOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2314365409751717571),
        name: 'type',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(23, 2702649130396046579),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 2542087586750132592),
    name: 'UserEntity',
    lastPropertyId: const obx_int.IdUid(37, 1413059307557799339),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6919948772852564858),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5642670880738263162),
        name: 'userId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(20, 857902389824920595),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4334401332539438957),
        name: 'email',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(21, 4792350814684409494),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4818806293931102842),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8675210534993946036),
        name: 'dateOfBirth',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7904833822245314895),
        name: 'gender',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5610871831769532420),
        name: 'lookingFor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8485321320564683929),
        name: 'bio',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4419850604041099640),
        name: 'profileCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 9075260570684807811),
        name: 'completionPercentage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2692359365794612776),
        name: 'occupation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7150576828542379870),
        name: 'interestsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8353897116030260845),
        name: 'heightCm',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8773832515839310214),
        name: 'education',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 490960495187266842),
        name: 'relationshipStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 5107408776990968384),
        name: 'city',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 6418426011000579424),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 8991084679507059486),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 419587109577645437),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 7408383919814988223),
        name: 'role',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(22, 5824882331433998595),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 6877015046132503144),
        name: 'lastActiveAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 7787594310917425671),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 4315712304766424671),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 3935773424819394564),
        name: 'accessToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 7182736512090360483),
        name: 'refreshToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 6377808560677613809),
        name: 'tokenExpiresAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 2235897222125071882),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 6214068144628207018),
        name: 'pendingActionsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 773594349407807086),
        name: 'interests',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 6308341353633730212),
        name: 'pendingActions',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 1413059307557799339),
        name: 'socialLinksJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(16, 2718134249710473670),
    name: 'GroupEntity',
    lastPropertyId: const obx_int.IdUid(13, 5150208962388941994),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7164979583769550632),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 163740708065132097),
        name: 'groupId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(51, 7525480722469569495),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2685821737914597732),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2895843931066133987),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2292080079517688250),
        name: 'photoUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5751355343038903544),
        name: 'creatorId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(52, 9175239330539719241),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1571803218169391025),
        name: 'memberIdsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7188328279242806796),
        name: 'memberCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4110631990348956582),
        name: 'category',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(53, 3727021616475047238),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5083574232633893431),
        name: 'isPrivate',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4107293063273300787),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2287705067238893163),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5150208962388941994),
        name: 'memberIds',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(17, 5477825036819035907),
    name: 'MatchEntity',
    lastPropertyId: const obx_int.IdUid(9, 4512188488071768411),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8923462981169296770),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6918895583722985977),
        name: 'matchId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(54, 8825996780236228221),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7910723660354230295),
        name: 'userId1',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(55, 512551908059747084),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9153364923797736334),
        name: 'userId2',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(56, 9179380293659650529),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8402476621719292523),
        name: 'status',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(57, 792553897871084876),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9173930539308954534),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8862460097826693935),
        name: 'matchedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8877527220308206840),
        name: 'user1Liked',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4512188488071768411),
        name: 'user2Liked',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(18, 634832648864528778),
    name: 'NotificationEntity',
    lastPropertyId: const obx_int.IdUid(12, 2188423085792069489),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5605819464066897388),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8319096815568017202),
        name: 'notificationId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(60, 2317351219609897270),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8282726495360899343),
        name: 'userId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(61, 4950832602061003012),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2100566791018648142),
        name: 'type',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(62, 7087456087125842364),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5627127849434743333),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4677462701977392435),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1276459773618451085),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8627795520093250350),
        name: 'actionRoute',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3701163688572015362),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6194132192372126974),
        name: 'isRead',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(63, 9207619792338848757),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8894887590987852746),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2188423085792069489),
        name: 'metadata',
        type: 13,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(19, 7169930160602577233),
    name: 'PreferenceEntity',
    lastPropertyId: const obx_int.IdUid(16, 3543718205400962223),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4774083251789059101),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9146836678443277974),
        name: 'userId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(64, 4059090069563892260),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1618157245523614029),
        name: 'minAge',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4176240330987875567),
        name: 'maxAge',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1324079989097580421),
        name: 'maxDistance',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6386463685412253669),
        name: 'genderPreferenceJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4970331464801237503),
        name: 'showOnlyVerified',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6423186684363103504),
        name: 'showOnlyWithPhotos',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 243980466563268506),
        name: 'notifyMatches',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7231017913375102830),
        name: 'notifyMessages',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3170357191089804543),
        name: 'notifyLikes',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2251998408889533032),
        name: 'showOnline',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8585436010703043135),
        name: 'showDistance',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4628138119785182493),
        name: 'incognitoMode',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4945799434254185709),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3543718205400962223),
        name: 'genderPreference',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(19, 7169930160602577233),
    lastIndexId: const obx_int.IdUid(64, 4059090069563892260),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      3464091729154190072,
      8823486773941683027,
      8975258110684548882,
      7939052532745188413,
      4994575106572718052,
      8836605362613854248,
      3399029600896283486,
      9085339953095138935,
      1708112871169753909,
      4031900605265696847,
      2182489560551608015,
      5758956572660440858,
    ],
    retiredIndexUids: const [
      166487482395153046,
      3352019510059169566,
      5318593113019861917,
      2624574982784093462,
      3732817562498762950,
      6748206779215418707,
      7033109480818725634,
      6090794998214863009,
    ],
    retiredPropertyUids: const [
      5809202638009700931,
      738783193934131447,
      1226735011396612119,
      5095512729598200616,
      7762687936498378608,
      7207592120041401552,
      3454965775106949629,
      4892096607378015477,
      6072928664057526634,
      7526650682297193840,
      4058134566031398088,
      7982324898679080309,
      4860468892107950045,
      5502468996464001780,
      2659528405513253917,
      433855757208762158,
      4206359709135488068,
      2266185473955135083,
      264942590326026317,
      8861879236087715931,
      1307370713424035531,
      5559852591035216075,
      5504600477552502291,
      5623521759347989156,
      927897435417654801,
      814897776231195416,
      8594304800740070109,
      596549956653931926,
      2084282370228247838,
      7257977895160972001,
      8211613575663351830,
      8813995437927844164,
      6596981966404069013,
      1749914576158415264,
      2927225328445424949,
      2787869346926142747,
      4679075621590370183,
      1894538548954603632,
      9154770973750994277,
      2951274490077827212,
      64095689851791749,
      411254399918300573,
      914846157871533012,
      7557651448323043048,
      1147212285518711019,
      6080813272548301072,
      4386960980732518177,
      4410309601441116222,
      2150254025431331507,
      1531012838708888084,
      8896944790703938091,
      1713058252576653399,
      2535895754249586911,
      7351287846114567084,
      7687911127148508489,
      1749405677318855193,
      3489490233085650421,
      2649557404428636982,
      7552553435907841086,
      4280398391983873141,
      4882043612379674661,
      5315639496394729121,
      4922253978389364818,
      510487057323735911,
      7144915604878216648,
      3218992018766008114,
      1645537589772899737,
      6878612092414600019,
      819157268244599432,
      4933264172165510497,
      7398556905329176224,
      8356743306196263124,
      1092776083168582361,
      7366966409018034161,
      3508664357147346664,
      3729634827221141465,
      3690187603343258951,
      988271890331729609,
      5696066217245688925,
      8954849477921163364,
      7575518887400219211,
      4447335247283159052,
      7642589053432512091,
      225675543630654248,
      1396039690781681807,
      28962974795244694,
      6972945656941698517,
      587975024576690062,
      8077977859225390734,
      1019692693750652720,
      8434418487605721004,
      2771012921991281962,
      5640456523076136028,
      6634619306711017764,
      8150426505909227236,
      6348531808163968201,
      7919560263981917945,
      4508882287115494499,
      7888328626885037352,
      3987365745285141100,
      5958928761508772498,
      9147966331361999149,
      3445934518942824499,
      5119778769197840648,
      7234025351180434091,
      7814858515384050851,
      1566634258215826178,
      5257269195083436873,
      8838174357832227640,
      2640340260394056274,
      1907377689382533354,
      5299015100136178970,
      5049744503618220925,
      7434190890192857557,
      9054440153232747308,
      1925884007840351038,
      5431561687158204835,
      2779286388156696052,
      3175889165207313701,
      5433846645123460226,
      8609025503902769205,
      7191551425063598938,
      7601501305402319630,
      4728613566780462479,
      3312825180414534291,
      6854866552231933736,
      2076246146737993630,
      1051421437093617476,
      7649053779064478082,
      5828930786527014941,
      6670294805912452930,
      3160641038894863500,
      1515991967266847986,
      6543163396874718263,
      2992917138548837975,
      4094829424893854867,
      3497261894056928659,
      8352237654346273050,
      4434642916518499377,
      2851153042171956074,
      6701132565143891173,
      7117090429836980649,
      2530378946732179276,
      167610027497529652,
      6666371553885115767,
      2513639892410666265,
      8211428666625127274,
      5477766894873171731,
      7125160830461464382,
      7869433043719532705,
      6930222885538294953,
      8557112594075041916,
      418632262167181082,
      4464013789602995473,
      4416569684032823643,
      2385391247107123364,
      6323981052876144905,
      4147374362463495526,
      1815777088843366446,
      5992700839083421613,
      664131478787339515,
      5201714423553872859,
      4627927393010258612,
      7133822594443658226,
      5337691074438051300,
      5352691203571593062,
      4170767953035657284,
      1919919234555376074,
      178554256875088473,
      2242839859048265977,
      8106878887244902873,
      2233391419614706163,
      1265661565640818604,
      4338038430297705082,
      325223828391484582,
      6862517649961653863,
      2787763929300000140,
      5464010685131167580,
      7675736336195198918,
      3129745599107722941,
      2162299234968845115,
      1423665266158328932,
      4579350975639166960,
      9083272555288265831,
      176090866203843578,
      3967259974204696039,
      2546478883189619866,
      2184442734398897122,
      5929307527286599798,
      5638138986342108398,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MessageEntity: obx_int.EntityDefinition<MessageEntity>(
      model: _entities[0],
      toOneRelations: (MessageEntity object) => [],
      toManyRelations: (MessageEntity object) => {},
      getId: (MessageEntity object) => object.id,
      setId: (MessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MessageEntity object, fb.Builder fbb) {
        final messageIdOffset = fbb.writeString(object.messageId);
        final senderIdOffset = fbb.writeString(object.senderId);
        final receiverIdOffset = fbb.writeString(object.receiverId);
        final contentOffset = fbb.writeString(object.content);
        final typeOffset = fbb.writeString(object.type);
        final attachmentUrlOffset = object.attachmentUrl == null
            ? null
            : fbb.writeString(object.attachmentUrl!);
        final attachmentLocalPathOffset = object.attachmentLocalPath == null
            ? null
            : fbb.writeString(object.attachmentLocalPath!);
        fbb.startTable(43);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, messageIdOffset);
        fbb.addOffset(2, senderIdOffset);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.readAt?.millisecondsSinceEpoch);
        fbb.addOffset(26, receiverIdOffset);
        fbb.addOffset(35, contentOffset);
        fbb.addOffset(36, typeOffset);
        fbb.addBool(37, object.isRead);
        fbb.addBool(38, object.isDelivered);
        fbb.addBool(39, object.isSent);
        fbb.addOffset(40, attachmentUrlOffset);
        fbb.addOffset(41, attachmentLocalPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final readAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final messageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final senderIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final receiverIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 56, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 74, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 76, '');
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          78,
          false,
        );
        final isDeliveredParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          80,
          false,
        );
        final isSentParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          82,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final readAtParam = readAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(readAtValue);
        final attachmentUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 84);
        final attachmentLocalPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 86);
        final object = MessageEntity(
          messageId: messageIdParam,
          senderId: senderIdParam,
          receiverId: receiverIdParam,
          content: contentParam,
          type: typeParam,
          isRead: isReadParam,
          isDelivered: isDeliveredParam,
          isSent: isSentParam,
          createdAt: createdAtParam,
          readAt: readAtParam,
          attachmentUrl: attachmentUrlParam,
          attachmentLocalPath: attachmentLocalPathParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    PhotoEntity: obx_int.EntityDefinition<PhotoEntity>(
      model: _entities[1],
      toOneRelations: (PhotoEntity object) => [],
      toManyRelations: (PhotoEntity object) => {},
      getId: (PhotoEntity object) => object.id,
      setId: (PhotoEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PhotoEntity object, fb.Builder fbb) {
        final photoIdOffset = fbb.writeString(object.photoId);
        final userIdOffset = fbb.writeString(object.userId);
        final localPathOffset = fbb.writeString(object.localPath);
        final remotePathOffset = object.remotePath == null
            ? null
            : fbb.writeString(object.remotePath!);
        final statusOffset = fbb.writeString(object.status);
        final moderatorIdOffset = object.moderatorId == null
            ? null
            : fbb.writeString(object.moderatorId!);
        final rejectionReasonOffset = object.rejectionReason == null
            ? null
            : fbb.writeString(object.rejectionReason!);
        final typeOffset = fbb.writeString(object.type);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, photoIdOffset);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, localPathOffset);
        fbb.addOffset(4, remotePathOffset);
        fbb.addOffset(5, statusOffset);
        fbb.addBool(6, object.hasWatermark);
        fbb.addInt64(7, object.uploadedAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.moderatedAt?.millisecondsSinceEpoch);
        fbb.addOffset(9, moderatorIdOffset);
        fbb.addOffset(10, rejectionReasonOffset);
        fbb.addInt64(12, object.displayOrder);
        fbb.addOffset(13, typeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final moderatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final photoIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final localPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final remotePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final hasWatermarkParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final uploadedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final moderatedAtParam = moderatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(moderatedAtValue);
        final moderatorIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final rejectionReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final displayOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final object = PhotoEntity(
          photoId: photoIdParam,
          userId: userIdParam,
          type: typeParam,
          localPath: localPathParam,
          remotePath: remotePathParam,
          status: statusParam,
          hasWatermark: hasWatermarkParam,
          uploadedAt: uploadedAtParam,
          moderatedAt: moderatedAtParam,
          moderatorId: moderatorIdParam,
          rejectionReason: rejectionReasonParam,
          displayOrder: displayOrderParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    UserEntity: obx_int.EntityDefinition<UserEntity>(
      model: _entities[2],
      toOneRelations: (UserEntity object) => [],
      toManyRelations: (UserEntity object) => {},
      getId: (UserEntity object) => object.id,
      setId: (UserEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final emailOffset = fbb.writeString(object.email);
        final fullNameOffset = object.fullName == null
            ? null
            : fbb.writeString(object.fullName!);
        final genderOffset = object.gender == null
            ? null
            : fbb.writeString(object.gender!);
        final lookingForOffset = object.lookingFor == null
            ? null
            : fbb.writeString(object.lookingFor!);
        final bioOffset = object.bio == null
            ? null
            : fbb.writeString(object.bio!);
        final occupationOffset = object.occupation == null
            ? null
            : fbb.writeString(object.occupation!);
        final interestsJsonOffset = fbb.writeString(object.interestsJson);
        final educationOffset = object.education == null
            ? null
            : fbb.writeString(object.education!);
        final relationshipStatusOffset = object.relationshipStatus == null
            ? null
            : fbb.writeString(object.relationshipStatus!);
        final cityOffset = object.city == null
            ? null
            : fbb.writeString(object.city!);
        final countryOffset = object.country == null
            ? null
            : fbb.writeString(object.country!);
        final roleOffset = fbb.writeString(object.role);
        final accessTokenOffset = object.accessToken == null
            ? null
            : fbb.writeString(object.accessToken!);
        final refreshTokenOffset = object.refreshToken == null
            ? null
            : fbb.writeString(object.refreshToken!);
        final pendingActionsJsonOffset = fbb.writeString(
          object.pendingActionsJson,
        );
        final interestsOffset = fbb.writeList(
          object.interests.map(fbb.writeString).toList(growable: false),
        );
        final pendingActionsOffset = fbb.writeList(
          object.pendingActions.map(fbb.writeString).toList(growable: false),
        );
        final socialLinksJsonOffset = fbb.writeString(object.socialLinksJson);
        fbb.startTable(38);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userIdOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, fullNameOffset);
        fbb.addInt64(4, object.dateOfBirth?.millisecondsSinceEpoch);
        fbb.addOffset(5, genderOffset);
        fbb.addOffset(6, lookingForOffset);
        fbb.addOffset(7, bioOffset);
        fbb.addBool(11, object.profileCompleted);
        fbb.addInt64(12, object.completionPercentage);
        fbb.addOffset(13, occupationOffset);
        fbb.addOffset(14, interestsJsonOffset);
        fbb.addInt64(15, object.heightCm);
        fbb.addOffset(16, educationOffset);
        fbb.addOffset(17, relationshipStatusOffset);
        fbb.addOffset(20, cityOffset);
        fbb.addOffset(21, countryOffset);
        fbb.addFloat64(22, object.latitude);
        fbb.addFloat64(23, object.longitude);
        fbb.addOffset(24, roleOffset);
        fbb.addInt64(25, object.lastActiveAt?.millisecondsSinceEpoch);
        fbb.addInt64(26, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(27, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(28, accessTokenOffset);
        fbb.addOffset(29, refreshTokenOffset);
        fbb.addInt64(30, object.tokenExpiresAt?.millisecondsSinceEpoch);
        fbb.addBool(31, object.needsSync);
        fbb.addOffset(32, pendingActionsJsonOffset);
        fbb.addOffset(34, interestsOffset);
        fbb.addOffset(35, pendingActionsOffset);
        fbb.addOffset(36, socialLinksJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateOfBirthValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final lastActiveAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          54,
        );
        final tokenExpiresAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          64,
        );
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final fullNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final dateOfBirthParam = dateOfBirthValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dateOfBirthValue);
        final genderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final lookingForParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final bioParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final profileCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final completionPercentageParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final occupationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final interestsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final heightCmParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final educationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final relationshipStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final socialLinksJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 76, '');
        final cityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 44);
        final countryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          48,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          50,
        );
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 52, '');
        final lastActiveAtParam = lastActiveAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastActiveAtValue);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 56, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 58, 0),
        );
        final accessTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 60);
        final refreshTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 62);
        final tokenExpiresAtParam = tokenExpiresAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(tokenExpiresAtValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          66,
          false,
        );
        final pendingActionsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 68, '');
        final object =
            UserEntity(
                userId: userIdParam,
                email: emailParam,
                fullName: fullNameParam,
                dateOfBirth: dateOfBirthParam,
                gender: genderParam,
                lookingFor: lookingForParam,
                bio: bioParam,
                profileCompleted: profileCompletedParam,
                completionPercentage: completionPercentageParam,
                occupation: occupationParam,
                interestsJson: interestsJsonParam,
                heightCm: heightCmParam,
                education: educationParam,
                relationshipStatus: relationshipStatusParam,
                socialLinksJson: socialLinksJsonParam,
                city: cityParam,
                country: countryParam,
                latitude: latitudeParam,
                longitude: longitudeParam,
                role: roleParam,
                lastActiveAt: lastActiveAtParam,
                createdAt: createdAtParam,
                updatedAt: updatedAtParam,
                accessToken: accessTokenParam,
                refreshToken: refreshTokenParam,
                tokenExpiresAt: tokenExpiresAtParam,
                needsSync: needsSyncParam,
                pendingActionsJson: pendingActionsJsonParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..interests = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 72, [])
              ..pendingActions = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 74, []);

        return object;
      },
    ),
    GroupEntity: obx_int.EntityDefinition<GroupEntity>(
      model: _entities[3],
      toOneRelations: (GroupEntity object) => [],
      toManyRelations: (GroupEntity object) => {},
      getId: (GroupEntity object) => object.id,
      setId: (GroupEntity object, int id) {
        object.id = id;
      },
      objectToFB: (GroupEntity object, fb.Builder fbb) {
        final groupIdOffset = fbb.writeString(object.groupId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final photoUrlOffset = object.photoUrl == null
            ? null
            : fbb.writeString(object.photoUrl!);
        final creatorIdOffset = fbb.writeString(object.creatorId);
        final memberIdsJsonOffset = fbb.writeString(object.memberIdsJson);
        final categoryOffset = fbb.writeString(object.category);
        final memberIdsOffset = fbb.writeList(
          object.memberIds.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, groupIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, photoUrlOffset);
        fbb.addOffset(5, creatorIdOffset);
        fbb.addOffset(6, memberIdsJsonOffset);
        fbb.addInt64(7, object.memberCount);
        fbb.addOffset(8, categoryOffset);
        fbb.addBool(9, object.isPrivate);
        fbb.addInt64(10, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(11, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(12, memberIdsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final groupIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final photoUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final creatorIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final memberIdsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final memberCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final isPrivateParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
        );
        final object =
            GroupEntity(
                groupId: groupIdParam,
                name: nameParam,
                description: descriptionParam,
                photoUrl: photoUrlParam,
                creatorId: creatorIdParam,
                memberIdsJson: memberIdsJsonParam,
                memberCount: memberCountParam,
                category: categoryParam,
                isPrivate: isPrivateParam,
                createdAt: createdAtParam,
                updatedAt: updatedAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..memberIds = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 28, []);

        return object;
      },
    ),
    MatchEntity: obx_int.EntityDefinition<MatchEntity>(
      model: _entities[4],
      toOneRelations: (MatchEntity object) => [],
      toManyRelations: (MatchEntity object) => {},
      getId: (MatchEntity object) => object.id,
      setId: (MatchEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MatchEntity object, fb.Builder fbb) {
        final matchIdOffset = fbb.writeString(object.matchId);
        final userId1Offset = fbb.writeString(object.userId1);
        final userId2Offset = fbb.writeString(object.userId2);
        final statusOffset = fbb.writeString(object.status);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, matchIdOffset);
        fbb.addOffset(2, userId1Offset);
        fbb.addOffset(3, userId2Offset);
        fbb.addOffset(4, statusOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.matchedAt?.millisecondsSinceEpoch);
        fbb.addBool(7, object.user1Liked);
        fbb.addBool(8, object.user2Liked);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final matchedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final matchIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userId1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final userId2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final matchedAtParam = matchedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(matchedAtValue);
        final user1LikedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final user2LikedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = MatchEntity(
          matchId: matchIdParam,
          userId1: userId1Param,
          userId2: userId2Param,
          status: statusParam,
          createdAt: createdAtParam,
          matchedAt: matchedAtParam,
          user1Liked: user1LikedParam,
          user2Liked: user2LikedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    NotificationEntity: obx_int.EntityDefinition<NotificationEntity>(
      model: _entities[5],
      toOneRelations: (NotificationEntity object) => [],
      toManyRelations: (NotificationEntity object) => {},
      getId: (NotificationEntity object) => object.id,
      setId: (NotificationEntity object, int id) {
        object.id = id;
      },
      objectToFB: (NotificationEntity object, fb.Builder fbb) {
        final notificationIdOffset = fbb.writeString(object.notificationId);
        final userIdOffset = fbb.writeString(object.userId);
        final typeOffset = fbb.writeString(object.type);
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = fbb.writeString(object.body);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        final actionRouteOffset = object.actionRoute == null
            ? null
            : fbb.writeString(object.actionRoute!);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        final metadataOffset = object.metadata == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.metadata!));
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, notificationIdOffset);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, titleOffset);
        fbb.addOffset(5, bodyOffset);
        fbb.addOffset(6, imageUrlOffset);
        fbb.addOffset(7, actionRouteOffset);
        fbb.addOffset(8, metadataJsonOffset);
        fbb.addBool(9, object.isRead);
        fbb.addInt64(10, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(11, metadataOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final notificationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final actionRouteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final object =
            NotificationEntity(
                notificationId: notificationIdParam,
                userId: userIdParam,
                type: typeParam,
                title: titleParam,
                body: bodyParam,
                imageUrl: imageUrlParam,
                actionRoute: actionRouteParam,
                metadataJson: metadataJsonParam,
                isRead: isReadParam,
                createdAt: createdAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..metadata = obx_int.flexBufferToMap(buffer, rootOffset, 26);

        return object;
      },
    ),
    PreferenceEntity: obx_int.EntityDefinition<PreferenceEntity>(
      model: _entities[6],
      toOneRelations: (PreferenceEntity object) => [],
      toManyRelations: (PreferenceEntity object) => {},
      getId: (PreferenceEntity object) => object.id,
      setId: (PreferenceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PreferenceEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final genderPreferenceJsonOffset = fbb.writeString(
          object.genderPreferenceJson,
        );
        final genderPreferenceOffset = fbb.writeList(
          object.genderPreference.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userIdOffset);
        fbb.addInt64(2, object.minAge);
        fbb.addInt64(3, object.maxAge);
        fbb.addInt64(4, object.maxDistance);
        fbb.addOffset(5, genderPreferenceJsonOffset);
        fbb.addBool(6, object.showOnlyVerified);
        fbb.addBool(7, object.showOnlyWithPhotos);
        fbb.addBool(8, object.notifyMatches);
        fbb.addBool(9, object.notifyMessages);
        fbb.addBool(10, object.notifyLikes);
        fbb.addBool(11, object.showOnline);
        fbb.addBool(12, object.showDistance);
        fbb.addBool(13, object.incognitoMode);
        fbb.addInt64(14, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(15, genderPreferenceOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final minAgeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final maxAgeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final maxDistanceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final genderPreferenceJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final showOnlyVerifiedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final showOnlyWithPhotosParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final notifyMatchesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final notifyMessagesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final notifyLikesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final showOnlineParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final showDistanceParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final incognitoModeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0),
        );
        final object =
            PreferenceEntity(
                userId: userIdParam,
                minAge: minAgeParam,
                maxAge: maxAgeParam,
                maxDistance: maxDistanceParam,
                genderPreferenceJson: genderPreferenceJsonParam,
                showOnlyVerified: showOnlyVerifiedParam,
                showOnlyWithPhotos: showOnlyWithPhotosParam,
                notifyMatches: notifyMatchesParam,
                notifyMessages: notifyMessagesParam,
                notifyLikes: notifyLikesParam,
                showOnline: showOnlineParam,
                showDistance: showDistanceParam,
                incognitoMode: incognitoModeParam,
                updatedAt: updatedAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..genderPreference = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 34, []);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MessageEntity] entity fields to define ObjectBox queries.
class MessageEntity_ {
  /// See [MessageEntity.id].
  static final id = obx.QueryIntegerProperty<MessageEntity>(
    _entities[0].properties[0],
  );

  /// See [MessageEntity.messageId].
  static final messageId = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[1],
  );

  /// See [MessageEntity.senderId].
  static final senderId = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[2],
  );

  /// See [MessageEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<MessageEntity>(
    _entities[0].properties[3],
  );

  /// See [MessageEntity.readAt].
  static final readAt = obx.QueryDateProperty<MessageEntity>(
    _entities[0].properties[4],
  );

  /// See [MessageEntity.receiverId].
  static final receiverId = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[5],
  );

  /// See [MessageEntity.content].
  static final content = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[6],
  );

  /// See [MessageEntity.type].
  static final type = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[7],
  );

  /// See [MessageEntity.isRead].
  static final isRead = obx.QueryBooleanProperty<MessageEntity>(
    _entities[0].properties[8],
  );

  /// See [MessageEntity.isDelivered].
  static final isDelivered = obx.QueryBooleanProperty<MessageEntity>(
    _entities[0].properties[9],
  );

  /// See [MessageEntity.isSent].
  static final isSent = obx.QueryBooleanProperty<MessageEntity>(
    _entities[0].properties[10],
  );

  /// See [MessageEntity.attachmentUrl].
  static final attachmentUrl = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[11],
  );

  /// See [MessageEntity.attachmentLocalPath].
  static final attachmentLocalPath = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[12],
  );
}

/// [PhotoEntity] entity fields to define ObjectBox queries.
class PhotoEntity_ {
  /// See [PhotoEntity.id].
  static final id = obx.QueryIntegerProperty<PhotoEntity>(
    _entities[1].properties[0],
  );

  /// See [PhotoEntity.photoId].
  static final photoId = obx.QueryStringProperty<PhotoEntity>(
    _entities[1].properties[1],
  );

  /// See [PhotoEntity.userId].
  static final userId = obx.QueryStringProperty<PhotoEntity>(
    _entities[1].properties[2],
  );

  /// See [PhotoEntity.localPath].
  static final localPath = obx.QueryStringProperty<PhotoEntity>(
    _entities[1].properties[3],
  );

  /// See [PhotoEntity.remotePath].
  static final remotePath = obx.QueryStringProperty<PhotoEntity>(
    _entities[1].properties[4],
  );

  /// See [PhotoEntity.status].
  static final status = obx.QueryStringProperty<PhotoEntity>(
    _entities[1].properties[5],
  );

  /// See [PhotoEntity.hasWatermark].
  static final hasWatermark = obx.QueryBooleanProperty<PhotoEntity>(
    _entities[1].properties[6],
  );

  /// See [PhotoEntity.uploadedAt].
  static final uploadedAt = obx.QueryDateProperty<PhotoEntity>(
    _entities[1].properties[7],
  );

  /// See [PhotoEntity.moderatedAt].
  static final moderatedAt = obx.QueryDateProperty<PhotoEntity>(
    _entities[1].properties[8],
  );

  /// See [PhotoEntity.moderatorId].
  static final moderatorId = obx.QueryStringProperty<PhotoEntity>(
    _entities[1].properties[9],
  );

  /// See [PhotoEntity.rejectionReason].
  static final rejectionReason = obx.QueryStringProperty<PhotoEntity>(
    _entities[1].properties[10],
  );

  /// See [PhotoEntity.displayOrder].
  static final displayOrder = obx.QueryIntegerProperty<PhotoEntity>(
    _entities[1].properties[11],
  );

  /// See [PhotoEntity.type].
  static final type = obx.QueryStringProperty<PhotoEntity>(
    _entities[1].properties[12],
  );
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// See [UserEntity.id].
  static final id = obx.QueryIntegerProperty<UserEntity>(
    _entities[2].properties[0],
  );

  /// See [UserEntity.userId].
  static final userId = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[1],
  );

  /// See [UserEntity.email].
  static final email = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[2],
  );

  /// See [UserEntity.fullName].
  static final fullName = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[3],
  );

  /// See [UserEntity.dateOfBirth].
  static final dateOfBirth = obx.QueryDateProperty<UserEntity>(
    _entities[2].properties[4],
  );

  /// See [UserEntity.gender].
  static final gender = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[5],
  );

  /// See [UserEntity.lookingFor].
  static final lookingFor = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[6],
  );

  /// See [UserEntity.bio].
  static final bio = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[7],
  );

  /// See [UserEntity.profileCompleted].
  static final profileCompleted = obx.QueryBooleanProperty<UserEntity>(
    _entities[2].properties[8],
  );

  /// See [UserEntity.completionPercentage].
  static final completionPercentage = obx.QueryIntegerProperty<UserEntity>(
    _entities[2].properties[9],
  );

  /// See [UserEntity.occupation].
  static final occupation = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[10],
  );

  /// See [UserEntity.interestsJson].
  static final interestsJson = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[11],
  );

  /// See [UserEntity.heightCm].
  static final heightCm = obx.QueryIntegerProperty<UserEntity>(
    _entities[2].properties[12],
  );

  /// See [UserEntity.education].
  static final education = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[13],
  );

  /// See [UserEntity.relationshipStatus].
  static final relationshipStatus = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[14],
  );

  /// See [UserEntity.city].
  static final city = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[15],
  );

  /// See [UserEntity.country].
  static final country = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[16],
  );

  /// See [UserEntity.latitude].
  static final latitude = obx.QueryDoubleProperty<UserEntity>(
    _entities[2].properties[17],
  );

  /// See [UserEntity.longitude].
  static final longitude = obx.QueryDoubleProperty<UserEntity>(
    _entities[2].properties[18],
  );

  /// See [UserEntity.role].
  static final role = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[19],
  );

  /// See [UserEntity.lastActiveAt].
  static final lastActiveAt = obx.QueryDateProperty<UserEntity>(
    _entities[2].properties[20],
  );

  /// See [UserEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<UserEntity>(
    _entities[2].properties[21],
  );

  /// See [UserEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<UserEntity>(
    _entities[2].properties[22],
  );

  /// See [UserEntity.accessToken].
  static final accessToken = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[23],
  );

  /// See [UserEntity.refreshToken].
  static final refreshToken = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[24],
  );

  /// See [UserEntity.tokenExpiresAt].
  static final tokenExpiresAt = obx.QueryDateProperty<UserEntity>(
    _entities[2].properties[25],
  );

  /// See [UserEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<UserEntity>(
    _entities[2].properties[26],
  );

  /// See [UserEntity.pendingActionsJson].
  static final pendingActionsJson = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[27],
  );

  /// See [UserEntity.interests].
  static final interests = obx.QueryStringVectorProperty<UserEntity>(
    _entities[2].properties[28],
  );

  /// See [UserEntity.pendingActions].
  static final pendingActions = obx.QueryStringVectorProperty<UserEntity>(
    _entities[2].properties[29],
  );

  /// See [UserEntity.socialLinksJson].
  static final socialLinksJson = obx.QueryStringProperty<UserEntity>(
    _entities[2].properties[30],
  );
}

/// [GroupEntity] entity fields to define ObjectBox queries.
class GroupEntity_ {
  /// See [GroupEntity.id].
  static final id = obx.QueryIntegerProperty<GroupEntity>(
    _entities[3].properties[0],
  );

  /// See [GroupEntity.groupId].
  static final groupId = obx.QueryStringProperty<GroupEntity>(
    _entities[3].properties[1],
  );

  /// See [GroupEntity.name].
  static final name = obx.QueryStringProperty<GroupEntity>(
    _entities[3].properties[2],
  );

  /// See [GroupEntity.description].
  static final description = obx.QueryStringProperty<GroupEntity>(
    _entities[3].properties[3],
  );

  /// See [GroupEntity.photoUrl].
  static final photoUrl = obx.QueryStringProperty<GroupEntity>(
    _entities[3].properties[4],
  );

  /// See [GroupEntity.creatorId].
  static final creatorId = obx.QueryStringProperty<GroupEntity>(
    _entities[3].properties[5],
  );

  /// See [GroupEntity.memberIdsJson].
  static final memberIdsJson = obx.QueryStringProperty<GroupEntity>(
    _entities[3].properties[6],
  );

  /// See [GroupEntity.memberCount].
  static final memberCount = obx.QueryIntegerProperty<GroupEntity>(
    _entities[3].properties[7],
  );

  /// See [GroupEntity.category].
  static final category = obx.QueryStringProperty<GroupEntity>(
    _entities[3].properties[8],
  );

  /// See [GroupEntity.isPrivate].
  static final isPrivate = obx.QueryBooleanProperty<GroupEntity>(
    _entities[3].properties[9],
  );

  /// See [GroupEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<GroupEntity>(
    _entities[3].properties[10],
  );

  /// See [GroupEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<GroupEntity>(
    _entities[3].properties[11],
  );

  /// See [GroupEntity.memberIds].
  static final memberIds = obx.QueryStringVectorProperty<GroupEntity>(
    _entities[3].properties[12],
  );
}

/// [MatchEntity] entity fields to define ObjectBox queries.
class MatchEntity_ {
  /// See [MatchEntity.id].
  static final id = obx.QueryIntegerProperty<MatchEntity>(
    _entities[4].properties[0],
  );

  /// See [MatchEntity.matchId].
  static final matchId = obx.QueryStringProperty<MatchEntity>(
    _entities[4].properties[1],
  );

  /// See [MatchEntity.userId1].
  static final userId1 = obx.QueryStringProperty<MatchEntity>(
    _entities[4].properties[2],
  );

  /// See [MatchEntity.userId2].
  static final userId2 = obx.QueryStringProperty<MatchEntity>(
    _entities[4].properties[3],
  );

  /// See [MatchEntity.status].
  static final status = obx.QueryStringProperty<MatchEntity>(
    _entities[4].properties[4],
  );

  /// See [MatchEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<MatchEntity>(
    _entities[4].properties[5],
  );

  /// See [MatchEntity.matchedAt].
  static final matchedAt = obx.QueryDateProperty<MatchEntity>(
    _entities[4].properties[6],
  );

  /// See [MatchEntity.user1Liked].
  static final user1Liked = obx.QueryBooleanProperty<MatchEntity>(
    _entities[4].properties[7],
  );

  /// See [MatchEntity.user2Liked].
  static final user2Liked = obx.QueryBooleanProperty<MatchEntity>(
    _entities[4].properties[8],
  );
}

/// [NotificationEntity] entity fields to define ObjectBox queries.
class NotificationEntity_ {
  /// See [NotificationEntity.id].
  static final id = obx.QueryIntegerProperty<NotificationEntity>(
    _entities[5].properties[0],
  );

  /// See [NotificationEntity.notificationId].
  static final notificationId = obx.QueryStringProperty<NotificationEntity>(
    _entities[5].properties[1],
  );

  /// See [NotificationEntity.userId].
  static final userId = obx.QueryStringProperty<NotificationEntity>(
    _entities[5].properties[2],
  );

  /// See [NotificationEntity.type].
  static final type = obx.QueryStringProperty<NotificationEntity>(
    _entities[5].properties[3],
  );

  /// See [NotificationEntity.title].
  static final title = obx.QueryStringProperty<NotificationEntity>(
    _entities[5].properties[4],
  );

  /// See [NotificationEntity.body].
  static final body = obx.QueryStringProperty<NotificationEntity>(
    _entities[5].properties[5],
  );

  /// See [NotificationEntity.imageUrl].
  static final imageUrl = obx.QueryStringProperty<NotificationEntity>(
    _entities[5].properties[6],
  );

  /// See [NotificationEntity.actionRoute].
  static final actionRoute = obx.QueryStringProperty<NotificationEntity>(
    _entities[5].properties[7],
  );

  /// See [NotificationEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<NotificationEntity>(
    _entities[5].properties[8],
  );

  /// See [NotificationEntity.isRead].
  static final isRead = obx.QueryBooleanProperty<NotificationEntity>(
    _entities[5].properties[9],
  );

  /// See [NotificationEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<NotificationEntity>(
    _entities[5].properties[10],
  );
}

/// [PreferenceEntity] entity fields to define ObjectBox queries.
class PreferenceEntity_ {
  /// See [PreferenceEntity.id].
  static final id = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[6].properties[0],
  );

  /// See [PreferenceEntity.userId].
  static final userId = obx.QueryStringProperty<PreferenceEntity>(
    _entities[6].properties[1],
  );

  /// See [PreferenceEntity.minAge].
  static final minAge = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[6].properties[2],
  );

  /// See [PreferenceEntity.maxAge].
  static final maxAge = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[6].properties[3],
  );

  /// See [PreferenceEntity.maxDistance].
  static final maxDistance = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[6].properties[4],
  );

  /// See [PreferenceEntity.genderPreferenceJson].
  static final genderPreferenceJson = obx.QueryStringProperty<PreferenceEntity>(
    _entities[6].properties[5],
  );

  /// See [PreferenceEntity.showOnlyVerified].
  static final showOnlyVerified = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[6].properties[6],
  );

  /// See [PreferenceEntity.showOnlyWithPhotos].
  static final showOnlyWithPhotos = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[6].properties[7],
  );

  /// See [PreferenceEntity.notifyMatches].
  static final notifyMatches = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[6].properties[8],
  );

  /// See [PreferenceEntity.notifyMessages].
  static final notifyMessages = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[6].properties[9],
  );

  /// See [PreferenceEntity.notifyLikes].
  static final notifyLikes = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[6].properties[10],
  );

  /// See [PreferenceEntity.showOnline].
  static final showOnline = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[6].properties[11],
  );

  /// See [PreferenceEntity.showDistance].
  static final showDistance = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[6].properties[12],
  );

  /// See [PreferenceEntity.incognitoMode].
  static final incognitoMode = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[6].properties[13],
  );

  /// See [PreferenceEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<PreferenceEntity>(
    _entities[6].properties[14],
  );

  /// See [PreferenceEntity.genderPreference].
  static final genderPreference =
      obx.QueryStringVectorProperty<PreferenceEntity>(
        _entities[6].properties[15],
      );
}
