// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'objectbox_entities_complete.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3464091729154190072),
    name: 'GroupEntity',
    lastPropertyId: const obx_int.IdUid(13, 64095689851791749),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2084282370228247838),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7257977895160972001),
        name: 'groupId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 8754440755102296845),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8211613575663351830),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8813995437927844164),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6596981966404069013),
        name: 'photoUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1749914576158415264),
        name: 'creatorId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 3815758378065823097),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2927225328445424949),
        name: 'memberIdsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2787869346926142747),
        name: 'memberCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4679075621590370183),
        name: 'category',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 87041381822000312),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1894538548954603632),
        name: 'isPrivate',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 9154770973750994277),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2951274490077827212),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 64095689851791749),
        name: 'memberIds',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8823486773941683027),
    name: 'MatchEntity',
    lastPropertyId: const obx_int.IdUid(9, 1531012838708888084),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 411254399918300573),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 914846157871533012),
        name: 'matchId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 6095293799653668522),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7557651448323043048),
        name: 'userId1',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 3515158751447650820),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1147212285518711019),
        name: 'userId2',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 521746829038624874),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6080813272548301072),
        name: 'status',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 2598419961610244628),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4386960980732518177),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4410309601441116222),
        name: 'matchedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2150254025431331507),
        name: 'user1Liked',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1531012838708888084),
        name: 'user2Liked',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5467978026615599515),
    name: 'MessageEntity',
    lastPropertyId: const obx_int.IdUid(13, 5502468996464001780),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3770034241375713903),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2248947782106369079),
        name: 'messageId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 9180704768471713073),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3373707912520330813),
        name: 'senderId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 6128137228116313680),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4892096607378015477),
        name: 'receiverId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 166487482395153046),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6072928664057526634),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2659528405513253917),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7526650682297193840),
        name: 'isRead',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(11, 3352019510059169566),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4058134566031398088),
        name: 'isDelivered',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7982324898679080309),
        name: 'isSent',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1412011340755810765),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2119918857659501308),
        name: 'readAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4860468892107950045),
        name: 'attachmentUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5502468996464001780),
        name: 'attachmentLocalPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8975258110684548882),
    name: 'NotificationEntity',
    lastPropertyId: const obx_int.IdUid(12, 5315639496394729121),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8896944790703938091),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1713058252576653399),
        name: 'notificationId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(12, 5893871017606699741),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2535895754249586911),
        name: 'userId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(13, 4243966182621126546),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7351287846114567084),
        name: 'type',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 348418793856179114),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7687911127148508489),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1749405677318855193),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3489490233085650421),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2649557404428636982),
        name: 'actionRoute',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7552553435907841086),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4280398391983873141),
        name: 'isRead',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(15, 4862451559777379367),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4882043612379674661),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5315639496394729121),
        name: 'metadata',
        type: 13,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1399498260393424036),
    name: 'PhotoEntity',
    lastPropertyId: const obx_int.IdUid(13, 4892388847827283425),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6562582849911528941),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5629970817789266956),
        name: 'photoId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(16, 4284453412325532584),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2552374184513372287),
        name: 'userId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(17, 623974254304267584),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4178087176773436485),
        name: 'localPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4527806955610173001),
        name: 'remotePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 74258813998320859),
        name: 'status',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(18, 8137819162317204723),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5652102618559000540),
        name: 'hasWatermark',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8849191550789706887),
        name: 'uploadedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6370112002516753636),
        name: 'moderatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6568229330521650249),
        name: 'moderatorId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1291879191982192012),
        name: 'rejectionReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5809202638009700931),
        name: 'isProfilePhoto',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4892388847827283425),
        name: 'displayOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7939052532745188413),
    name: 'PreferenceEntity',
    lastPropertyId: const obx_int.IdUid(16, 988271890331729609),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4922253978389364818),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 510487057323735911),
        name: 'userId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(19, 2717711902166914824),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7144915604878216648),
        name: 'minAge',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3218992018766008114),
        name: 'maxAge',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1645537589772899737),
        name: 'maxDistance',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6878612092414600019),
        name: 'genderPreferenceJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 819157268244599432),
        name: 'showOnlyVerified',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4933264172165510497),
        name: 'showOnlyWithPhotos',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7398556905329176224),
        name: 'notifyMatches',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8356743306196263124),
        name: 'notifyMessages',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1092776083168582361),
        name: 'notifyLikes',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7366966409018034161),
        name: 'showOnline',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3508664357147346664),
        name: 'showDistance',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3729634827221141465),
        name: 'incognitoMode',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3690187603343258951),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 988271890331729609),
        name: 'genderPreference',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 2542087586750132592),
    name: 'UserEntity',
    lastPropertyId: const obx_int.IdUid(36, 6308341353633730212),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6919948772852564858),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5642670880738263162),
        name: 'userId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(20, 857902389824920595),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4334401332539438957),
        name: 'email',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(21, 4792350814684409494),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4818806293931102842),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8675210534993946036),
        name: 'dateOfBirth',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7904833822245314895),
        name: 'gender',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5610871831769532420),
        name: 'lookingFor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8485321320564683929),
        name: 'bio',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 738783193934131447),
        name: 'photosJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1226735011396612119),
        name: 'photoUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5095512729598200616),
        name: 'coverUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4419850604041099640),
        name: 'profileCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 9075260570684807811),
        name: 'completionPercentage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2692359365794612776),
        name: 'occupation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7150576828542379870),
        name: 'interestsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8353897116030260845),
        name: 'heightCm',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8773832515839310214),
        name: 'education',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 490960495187266842),
        name: 'relationshipStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 7762687936498378608),
        name: 'instagramHandle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 7207592120041401552),
        name: 'spotifyAnthem',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 5107408776990968384),
        name: 'city',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 6418426011000579424),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 8991084679507059486),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 419587109577645437),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 7408383919814988223),
        name: 'role',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(22, 5824882331433998595),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 6877015046132503144),
        name: 'lastActiveAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 7787594310917425671),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 4315712304766424671),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 3935773424819394564),
        name: 'accessToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 7182736512090360483),
        name: 'refreshToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 6377808560677613809),
        name: 'tokenExpiresAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 2235897222125071882),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 6214068144628207018),
        name: 'pendingActionsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 3454965775106949629),
        name: 'photos',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 773594349407807086),
        name: 'interests',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 6308341353633730212),
        name: 'pendingActions',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 2542087586750132592),
    lastIndexId: const obx_int.IdUid(22, 5824882331433998595),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    GroupEntity: obx_int.EntityDefinition<GroupEntity>(
      model: _entities[0],
      toOneRelations: (GroupEntity object) => [],
      toManyRelations: (GroupEntity object) => {},
      getId: (GroupEntity object) => object.id,
      setId: (GroupEntity object, int id) {
        object.id = id;
      },
      objectToFB: (GroupEntity object, fb.Builder fbb) {
        final groupIdOffset = fbb.writeString(object.groupId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final photoUrlOffset = object.photoUrl == null
            ? null
            : fbb.writeString(object.photoUrl!);
        final creatorIdOffset = fbb.writeString(object.creatorId);
        final memberIdsJsonOffset = fbb.writeString(object.memberIdsJson);
        final categoryOffset = fbb.writeString(object.category);
        final memberIdsOffset = fbb.writeList(
          object.memberIds.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, groupIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, photoUrlOffset);
        fbb.addOffset(5, creatorIdOffset);
        fbb.addOffset(6, memberIdsJsonOffset);
        fbb.addInt64(7, object.memberCount);
        fbb.addOffset(8, categoryOffset);
        fbb.addBool(9, object.isPrivate);
        fbb.addInt64(10, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(11, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(12, memberIdsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final groupIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final photoUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final creatorIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final memberIdsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final memberCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final isPrivateParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
        );
        final object =
            GroupEntity(
                groupId: groupIdParam,
                name: nameParam,
                description: descriptionParam,
                photoUrl: photoUrlParam,
                creatorId: creatorIdParam,
                memberIdsJson: memberIdsJsonParam,
                memberCount: memberCountParam,
                category: categoryParam,
                isPrivate: isPrivateParam,
                createdAt: createdAtParam,
                updatedAt: updatedAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..memberIds = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 28, []);

        return object;
      },
    ),
    MatchEntity: obx_int.EntityDefinition<MatchEntity>(
      model: _entities[1],
      toOneRelations: (MatchEntity object) => [],
      toManyRelations: (MatchEntity object) => {},
      getId: (MatchEntity object) => object.id,
      setId: (MatchEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MatchEntity object, fb.Builder fbb) {
        final matchIdOffset = fbb.writeString(object.matchId);
        final userId1Offset = fbb.writeString(object.userId1);
        final userId2Offset = fbb.writeString(object.userId2);
        final statusOffset = fbb.writeString(object.status);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, matchIdOffset);
        fbb.addOffset(2, userId1Offset);
        fbb.addOffset(3, userId2Offset);
        fbb.addOffset(4, statusOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.matchedAt?.millisecondsSinceEpoch);
        fbb.addBool(7, object.user1Liked);
        fbb.addBool(8, object.user2Liked);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final matchedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final matchIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userId1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final userId2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final matchedAtParam = matchedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(matchedAtValue);
        final user1LikedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final user2LikedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = MatchEntity(
          matchId: matchIdParam,
          userId1: userId1Param,
          userId2: userId2Param,
          status: statusParam,
          createdAt: createdAtParam,
          matchedAt: matchedAtParam,
          user1Liked: user1LikedParam,
          user2Liked: user2LikedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    MessageEntity: obx_int.EntityDefinition<MessageEntity>(
      model: _entities[2],
      toOneRelations: (MessageEntity object) => [],
      toManyRelations: (MessageEntity object) => {},
      getId: (MessageEntity object) => object.id,
      setId: (MessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MessageEntity object, fb.Builder fbb) {
        final messageIdOffset = fbb.writeString(object.messageId);
        final senderIdOffset = fbb.writeString(object.senderId);
        final receiverIdOffset = fbb.writeString(object.receiverId);
        final contentOffset = fbb.writeString(object.content);
        final typeOffset = fbb.writeString(object.type);
        final attachmentUrlOffset = object.attachmentUrl == null
            ? null
            : fbb.writeString(object.attachmentUrl!);
        final attachmentLocalPathOffset = object.attachmentLocalPath == null
            ? null
            : fbb.writeString(object.attachmentLocalPath!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, messageIdOffset);
        fbb.addOffset(2, senderIdOffset);
        fbb.addOffset(3, receiverIdOffset);
        fbb.addOffset(4, contentOffset);
        fbb.addOffset(5, typeOffset);
        fbb.addBool(6, object.isRead);
        fbb.addBool(7, object.isDelivered);
        fbb.addBool(8, object.isSent);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.readAt?.millisecondsSinceEpoch);
        fbb.addOffset(11, attachmentUrlOffset);
        fbb.addOffset(12, attachmentLocalPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final readAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final messageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final senderIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final receiverIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final isDeliveredParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isSentParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final readAtParam = readAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(readAtValue);
        final attachmentUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final attachmentLocalPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final object = MessageEntity(
          messageId: messageIdParam,
          senderId: senderIdParam,
          receiverId: receiverIdParam,
          content: contentParam,
          type: typeParam,
          isRead: isReadParam,
          isDelivered: isDeliveredParam,
          isSent: isSentParam,
          createdAt: createdAtParam,
          readAt: readAtParam,
          attachmentUrl: attachmentUrlParam,
          attachmentLocalPath: attachmentLocalPathParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    NotificationEntity: obx_int.EntityDefinition<NotificationEntity>(
      model: _entities[3],
      toOneRelations: (NotificationEntity object) => [],
      toManyRelations: (NotificationEntity object) => {},
      getId: (NotificationEntity object) => object.id,
      setId: (NotificationEntity object, int id) {
        object.id = id;
      },
      objectToFB: (NotificationEntity object, fb.Builder fbb) {
        final notificationIdOffset = fbb.writeString(object.notificationId);
        final userIdOffset = fbb.writeString(object.userId);
        final typeOffset = fbb.writeString(object.type);
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = fbb.writeString(object.body);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        final actionRouteOffset = object.actionRoute == null
            ? null
            : fbb.writeString(object.actionRoute!);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        final metadataOffset = object.metadata == null
            ? null
            : fbb.writeListInt8(obx_int.toFlexBuffer(object.metadata!));
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, notificationIdOffset);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, titleOffset);
        fbb.addOffset(5, bodyOffset);
        fbb.addOffset(6, imageUrlOffset);
        fbb.addOffset(7, actionRouteOffset);
        fbb.addOffset(8, metadataJsonOffset);
        fbb.addBool(9, object.isRead);
        fbb.addInt64(10, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(11, metadataOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final notificationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final actionRouteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final object =
            NotificationEntity(
                notificationId: notificationIdParam,
                userId: userIdParam,
                type: typeParam,
                title: titleParam,
                body: bodyParam,
                imageUrl: imageUrlParam,
                actionRoute: actionRouteParam,
                metadataJson: metadataJsonParam,
                isRead: isReadParam,
                createdAt: createdAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..metadata = obx_int.flexBufferToMap(buffer, rootOffset, 26);

        return object;
      },
    ),
    PhotoEntity: obx_int.EntityDefinition<PhotoEntity>(
      model: _entities[4],
      toOneRelations: (PhotoEntity object) => [],
      toManyRelations: (PhotoEntity object) => {},
      getId: (PhotoEntity object) => object.id,
      setId: (PhotoEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PhotoEntity object, fb.Builder fbb) {
        final photoIdOffset = fbb.writeString(object.photoId);
        final userIdOffset = fbb.writeString(object.userId);
        final localPathOffset = fbb.writeString(object.localPath);
        final remotePathOffset = object.remotePath == null
            ? null
            : fbb.writeString(object.remotePath!);
        final statusOffset = fbb.writeString(object.status);
        final moderatorIdOffset = object.moderatorId == null
            ? null
            : fbb.writeString(object.moderatorId!);
        final rejectionReasonOffset = object.rejectionReason == null
            ? null
            : fbb.writeString(object.rejectionReason!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, photoIdOffset);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, localPathOffset);
        fbb.addOffset(4, remotePathOffset);
        fbb.addOffset(5, statusOffset);
        fbb.addBool(6, object.hasWatermark);
        fbb.addInt64(7, object.uploadedAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.moderatedAt?.millisecondsSinceEpoch);
        fbb.addOffset(9, moderatorIdOffset);
        fbb.addOffset(10, rejectionReasonOffset);
        fbb.addBool(11, object.isProfilePhoto);
        fbb.addInt64(12, object.displayOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final moderatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final photoIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final localPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final remotePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final hasWatermarkParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final uploadedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final moderatedAtParam = moderatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(moderatedAtValue);
        final moderatorIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final rejectionReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final isProfilePhotoParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final displayOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final object = PhotoEntity(
          photoId: photoIdParam,
          userId: userIdParam,
          localPath: localPathParam,
          remotePath: remotePathParam,
          status: statusParam,
          hasWatermark: hasWatermarkParam,
          uploadedAt: uploadedAtParam,
          moderatedAt: moderatedAtParam,
          moderatorId: moderatorIdParam,
          rejectionReason: rejectionReasonParam,
          isProfilePhoto: isProfilePhotoParam,
          displayOrder: displayOrderParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    PreferenceEntity: obx_int.EntityDefinition<PreferenceEntity>(
      model: _entities[5],
      toOneRelations: (PreferenceEntity object) => [],
      toManyRelations: (PreferenceEntity object) => {},
      getId: (PreferenceEntity object) => object.id,
      setId: (PreferenceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PreferenceEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final genderPreferenceJsonOffset = fbb.writeString(
          object.genderPreferenceJson,
        );
        final genderPreferenceOffset = fbb.writeList(
          object.genderPreference.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userIdOffset);
        fbb.addInt64(2, object.minAge);
        fbb.addInt64(3, object.maxAge);
        fbb.addInt64(4, object.maxDistance);
        fbb.addOffset(5, genderPreferenceJsonOffset);
        fbb.addBool(6, object.showOnlyVerified);
        fbb.addBool(7, object.showOnlyWithPhotos);
        fbb.addBool(8, object.notifyMatches);
        fbb.addBool(9, object.notifyMessages);
        fbb.addBool(10, object.notifyLikes);
        fbb.addBool(11, object.showOnline);
        fbb.addBool(12, object.showDistance);
        fbb.addBool(13, object.incognitoMode);
        fbb.addInt64(14, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(15, genderPreferenceOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final minAgeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final maxAgeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final maxDistanceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final genderPreferenceJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final showOnlyVerifiedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final showOnlyWithPhotosParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final notifyMatchesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final notifyMessagesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final notifyLikesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final showOnlineParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final showDistanceParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final incognitoModeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0),
        );
        final object =
            PreferenceEntity(
                userId: userIdParam,
                minAge: minAgeParam,
                maxAge: maxAgeParam,
                maxDistance: maxDistanceParam,
                genderPreferenceJson: genderPreferenceJsonParam,
                showOnlyVerified: showOnlyVerifiedParam,
                showOnlyWithPhotos: showOnlyWithPhotosParam,
                notifyMatches: notifyMatchesParam,
                notifyMessages: notifyMessagesParam,
                notifyLikes: notifyLikesParam,
                showOnline: showOnlineParam,
                showDistance: showDistanceParam,
                incognitoMode: incognitoModeParam,
                updatedAt: updatedAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..genderPreference = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 34, []);

        return object;
      },
    ),
    UserEntity: obx_int.EntityDefinition<UserEntity>(
      model: _entities[6],
      toOneRelations: (UserEntity object) => [],
      toManyRelations: (UserEntity object) => {},
      getId: (UserEntity object) => object.id,
      setId: (UserEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final emailOffset = fbb.writeString(object.email);
        final fullNameOffset = object.fullName == null
            ? null
            : fbb.writeString(object.fullName!);
        final genderOffset = object.gender == null
            ? null
            : fbb.writeString(object.gender!);
        final lookingForOffset = object.lookingFor == null
            ? null
            : fbb.writeString(object.lookingFor!);
        final bioOffset = object.bio == null
            ? null
            : fbb.writeString(object.bio!);
        final photosJsonOffset = fbb.writeString(object.photosJson);
        final photoUrlOffset = object.photoUrl == null
            ? null
            : fbb.writeString(object.photoUrl!);
        final coverUrlOffset = object.coverUrl == null
            ? null
            : fbb.writeString(object.coverUrl!);
        final occupationOffset = object.occupation == null
            ? null
            : fbb.writeString(object.occupation!);
        final interestsJsonOffset = fbb.writeString(object.interestsJson);
        final educationOffset = object.education == null
            ? null
            : fbb.writeString(object.education!);
        final relationshipStatusOffset = object.relationshipStatus == null
            ? null
            : fbb.writeString(object.relationshipStatus!);
        final instagramHandleOffset = object.instagramHandle == null
            ? null
            : fbb.writeString(object.instagramHandle!);
        final spotifyAnthemOffset = object.spotifyAnthem == null
            ? null
            : fbb.writeString(object.spotifyAnthem!);
        final cityOffset = object.city == null
            ? null
            : fbb.writeString(object.city!);
        final countryOffset = object.country == null
            ? null
            : fbb.writeString(object.country!);
        final roleOffset = fbb.writeString(object.role);
        final accessTokenOffset = object.accessToken == null
            ? null
            : fbb.writeString(object.accessToken!);
        final refreshTokenOffset = object.refreshToken == null
            ? null
            : fbb.writeString(object.refreshToken!);
        final pendingActionsJsonOffset = fbb.writeString(
          object.pendingActionsJson,
        );
        final photosOffset = fbb.writeList(
          object.photos.map(fbb.writeString).toList(growable: false),
        );
        final interestsOffset = fbb.writeList(
          object.interests.map(fbb.writeString).toList(growable: false),
        );
        final pendingActionsOffset = fbb.writeList(
          object.pendingActions.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(37);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userIdOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, fullNameOffset);
        fbb.addInt64(4, object.dateOfBirth?.millisecondsSinceEpoch);
        fbb.addOffset(5, genderOffset);
        fbb.addOffset(6, lookingForOffset);
        fbb.addOffset(7, bioOffset);
        fbb.addOffset(8, photosJsonOffset);
        fbb.addOffset(9, photoUrlOffset);
        fbb.addOffset(10, coverUrlOffset);
        fbb.addBool(11, object.profileCompleted);
        fbb.addInt64(12, object.completionPercentage);
        fbb.addOffset(13, occupationOffset);
        fbb.addOffset(14, interestsJsonOffset);
        fbb.addInt64(15, object.heightCm);
        fbb.addOffset(16, educationOffset);
        fbb.addOffset(17, relationshipStatusOffset);
        fbb.addOffset(18, instagramHandleOffset);
        fbb.addOffset(19, spotifyAnthemOffset);
        fbb.addOffset(20, cityOffset);
        fbb.addOffset(21, countryOffset);
        fbb.addFloat64(22, object.latitude);
        fbb.addFloat64(23, object.longitude);
        fbb.addOffset(24, roleOffset);
        fbb.addInt64(25, object.lastActiveAt?.millisecondsSinceEpoch);
        fbb.addInt64(26, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(27, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(28, accessTokenOffset);
        fbb.addOffset(29, refreshTokenOffset);
        fbb.addInt64(30, object.tokenExpiresAt?.millisecondsSinceEpoch);
        fbb.addBool(31, object.needsSync);
        fbb.addOffset(32, pendingActionsJsonOffset);
        fbb.addOffset(33, photosOffset);
        fbb.addOffset(34, interestsOffset);
        fbb.addOffset(35, pendingActionsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateOfBirthValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final lastActiveAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          54,
        );
        final tokenExpiresAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          64,
        );
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final fullNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final dateOfBirthParam = dateOfBirthValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dateOfBirthValue);
        final genderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final lookingForParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final bioParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final photosJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final photoUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final coverUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final profileCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final completionPercentageParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final occupationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final interestsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final heightCmParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final educationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final relationshipStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final instagramHandleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final spotifyAnthemParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final cityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 44);
        final countryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          48,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          50,
        );
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 52, '');
        final lastActiveAtParam = lastActiveAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastActiveAtValue);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 56, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 58, 0),
        );
        final accessTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 60);
        final refreshTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 62);
        final tokenExpiresAtParam = tokenExpiresAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(tokenExpiresAtValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          66,
          false,
        );
        final pendingActionsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 68, '');
        final object =
            UserEntity(
                userId: userIdParam,
                email: emailParam,
                fullName: fullNameParam,
                dateOfBirth: dateOfBirthParam,
                gender: genderParam,
                lookingFor: lookingForParam,
                bio: bioParam,
                photosJson: photosJsonParam,
                photoUrl: photoUrlParam,
                coverUrl: coverUrlParam,
                profileCompleted: profileCompletedParam,
                completionPercentage: completionPercentageParam,
                occupation: occupationParam,
                interestsJson: interestsJsonParam,
                heightCm: heightCmParam,
                education: educationParam,
                relationshipStatus: relationshipStatusParam,
                instagramHandle: instagramHandleParam,
                spotifyAnthem: spotifyAnthemParam,
                city: cityParam,
                country: countryParam,
                latitude: latitudeParam,
                longitude: longitudeParam,
                role: roleParam,
                lastActiveAt: lastActiveAtParam,
                createdAt: createdAtParam,
                updatedAt: updatedAtParam,
                accessToken: accessTokenParam,
                refreshToken: refreshTokenParam,
                tokenExpiresAt: tokenExpiresAtParam,
                needsSync: needsSyncParam,
                pendingActionsJson: pendingActionsJsonParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..photos = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 70, [])
              ..interests = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 72, [])
              ..pendingActions = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 74, []);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [GroupEntity] entity fields to define ObjectBox queries.
class GroupEntity_ {
  /// See [GroupEntity.id].
  static final id = obx.QueryIntegerProperty<GroupEntity>(
    _entities[0].properties[0],
  );

  /// See [GroupEntity.groupId].
  static final groupId = obx.QueryStringProperty<GroupEntity>(
    _entities[0].properties[1],
  );

  /// See [GroupEntity.name].
  static final name = obx.QueryStringProperty<GroupEntity>(
    _entities[0].properties[2],
  );

  /// See [GroupEntity.description].
  static final description = obx.QueryStringProperty<GroupEntity>(
    _entities[0].properties[3],
  );

  /// See [GroupEntity.photoUrl].
  static final photoUrl = obx.QueryStringProperty<GroupEntity>(
    _entities[0].properties[4],
  );

  /// See [GroupEntity.creatorId].
  static final creatorId = obx.QueryStringProperty<GroupEntity>(
    _entities[0].properties[5],
  );

  /// See [GroupEntity.memberIdsJson].
  static final memberIdsJson = obx.QueryStringProperty<GroupEntity>(
    _entities[0].properties[6],
  );

  /// See [GroupEntity.memberCount].
  static final memberCount = obx.QueryIntegerProperty<GroupEntity>(
    _entities[0].properties[7],
  );

  /// See [GroupEntity.category].
  static final category = obx.QueryStringProperty<GroupEntity>(
    _entities[0].properties[8],
  );

  /// See [GroupEntity.isPrivate].
  static final isPrivate = obx.QueryBooleanProperty<GroupEntity>(
    _entities[0].properties[9],
  );

  /// See [GroupEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<GroupEntity>(
    _entities[0].properties[10],
  );

  /// See [GroupEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<GroupEntity>(
    _entities[0].properties[11],
  );

  /// See [GroupEntity.memberIds].
  static final memberIds = obx.QueryStringVectorProperty<GroupEntity>(
    _entities[0].properties[12],
  );
}

/// [MatchEntity] entity fields to define ObjectBox queries.
class MatchEntity_ {
  /// See [MatchEntity.id].
  static final id = obx.QueryIntegerProperty<MatchEntity>(
    _entities[1].properties[0],
  );

  /// See [MatchEntity.matchId].
  static final matchId = obx.QueryStringProperty<MatchEntity>(
    _entities[1].properties[1],
  );

  /// See [MatchEntity.userId1].
  static final userId1 = obx.QueryStringProperty<MatchEntity>(
    _entities[1].properties[2],
  );

  /// See [MatchEntity.userId2].
  static final userId2 = obx.QueryStringProperty<MatchEntity>(
    _entities[1].properties[3],
  );

  /// See [MatchEntity.status].
  static final status = obx.QueryStringProperty<MatchEntity>(
    _entities[1].properties[4],
  );

  /// See [MatchEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<MatchEntity>(
    _entities[1].properties[5],
  );

  /// See [MatchEntity.matchedAt].
  static final matchedAt = obx.QueryDateProperty<MatchEntity>(
    _entities[1].properties[6],
  );

  /// See [MatchEntity.user1Liked].
  static final user1Liked = obx.QueryBooleanProperty<MatchEntity>(
    _entities[1].properties[7],
  );

  /// See [MatchEntity.user2Liked].
  static final user2Liked = obx.QueryBooleanProperty<MatchEntity>(
    _entities[1].properties[8],
  );
}

/// [MessageEntity] entity fields to define ObjectBox queries.
class MessageEntity_ {
  /// See [MessageEntity.id].
  static final id = obx.QueryIntegerProperty<MessageEntity>(
    _entities[2].properties[0],
  );

  /// See [MessageEntity.messageId].
  static final messageId = obx.QueryStringProperty<MessageEntity>(
    _entities[2].properties[1],
  );

  /// See [MessageEntity.senderId].
  static final senderId = obx.QueryStringProperty<MessageEntity>(
    _entities[2].properties[2],
  );

  /// See [MessageEntity.receiverId].
  static final receiverId = obx.QueryStringProperty<MessageEntity>(
    _entities[2].properties[3],
  );

  /// See [MessageEntity.content].
  static final content = obx.QueryStringProperty<MessageEntity>(
    _entities[2].properties[4],
  );

  /// See [MessageEntity.type].
  static final type = obx.QueryStringProperty<MessageEntity>(
    _entities[2].properties[5],
  );

  /// See [MessageEntity.isRead].
  static final isRead = obx.QueryBooleanProperty<MessageEntity>(
    _entities[2].properties[6],
  );

  /// See [MessageEntity.isDelivered].
  static final isDelivered = obx.QueryBooleanProperty<MessageEntity>(
    _entities[2].properties[7],
  );

  /// See [MessageEntity.isSent].
  static final isSent = obx.QueryBooleanProperty<MessageEntity>(
    _entities[2].properties[8],
  );

  /// See [MessageEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<MessageEntity>(
    _entities[2].properties[9],
  );

  /// See [MessageEntity.readAt].
  static final readAt = obx.QueryDateProperty<MessageEntity>(
    _entities[2].properties[10],
  );

  /// See [MessageEntity.attachmentUrl].
  static final attachmentUrl = obx.QueryStringProperty<MessageEntity>(
    _entities[2].properties[11],
  );

  /// See [MessageEntity.attachmentLocalPath].
  static final attachmentLocalPath = obx.QueryStringProperty<MessageEntity>(
    _entities[2].properties[12],
  );
}

/// [NotificationEntity] entity fields to define ObjectBox queries.
class NotificationEntity_ {
  /// See [NotificationEntity.id].
  static final id = obx.QueryIntegerProperty<NotificationEntity>(
    _entities[3].properties[0],
  );

  /// See [NotificationEntity.notificationId].
  static final notificationId = obx.QueryStringProperty<NotificationEntity>(
    _entities[3].properties[1],
  );

  /// See [NotificationEntity.userId].
  static final userId = obx.QueryStringProperty<NotificationEntity>(
    _entities[3].properties[2],
  );

  /// See [NotificationEntity.type].
  static final type = obx.QueryStringProperty<NotificationEntity>(
    _entities[3].properties[3],
  );

  /// See [NotificationEntity.title].
  static final title = obx.QueryStringProperty<NotificationEntity>(
    _entities[3].properties[4],
  );

  /// See [NotificationEntity.body].
  static final body = obx.QueryStringProperty<NotificationEntity>(
    _entities[3].properties[5],
  );

  /// See [NotificationEntity.imageUrl].
  static final imageUrl = obx.QueryStringProperty<NotificationEntity>(
    _entities[3].properties[6],
  );

  /// See [NotificationEntity.actionRoute].
  static final actionRoute = obx.QueryStringProperty<NotificationEntity>(
    _entities[3].properties[7],
  );

  /// See [NotificationEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<NotificationEntity>(
    _entities[3].properties[8],
  );

  /// See [NotificationEntity.isRead].
  static final isRead = obx.QueryBooleanProperty<NotificationEntity>(
    _entities[3].properties[9],
  );

  /// See [NotificationEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<NotificationEntity>(
    _entities[3].properties[10],
  );
}

/// [PhotoEntity] entity fields to define ObjectBox queries.
class PhotoEntity_ {
  /// See [PhotoEntity.id].
  static final id = obx.QueryIntegerProperty<PhotoEntity>(
    _entities[4].properties[0],
  );

  /// See [PhotoEntity.photoId].
  static final photoId = obx.QueryStringProperty<PhotoEntity>(
    _entities[4].properties[1],
  );

  /// See [PhotoEntity.userId].
  static final userId = obx.QueryStringProperty<PhotoEntity>(
    _entities[4].properties[2],
  );

  /// See [PhotoEntity.localPath].
  static final localPath = obx.QueryStringProperty<PhotoEntity>(
    _entities[4].properties[3],
  );

  /// See [PhotoEntity.remotePath].
  static final remotePath = obx.QueryStringProperty<PhotoEntity>(
    _entities[4].properties[4],
  );

  /// See [PhotoEntity.status].
  static final status = obx.QueryStringProperty<PhotoEntity>(
    _entities[4].properties[5],
  );

  /// See [PhotoEntity.hasWatermark].
  static final hasWatermark = obx.QueryBooleanProperty<PhotoEntity>(
    _entities[4].properties[6],
  );

  /// See [PhotoEntity.uploadedAt].
  static final uploadedAt = obx.QueryDateProperty<PhotoEntity>(
    _entities[4].properties[7],
  );

  /// See [PhotoEntity.moderatedAt].
  static final moderatedAt = obx.QueryDateProperty<PhotoEntity>(
    _entities[4].properties[8],
  );

  /// See [PhotoEntity.moderatorId].
  static final moderatorId = obx.QueryStringProperty<PhotoEntity>(
    _entities[4].properties[9],
  );

  /// See [PhotoEntity.rejectionReason].
  static final rejectionReason = obx.QueryStringProperty<PhotoEntity>(
    _entities[4].properties[10],
  );

  /// See [PhotoEntity.isProfilePhoto].
  static final isProfilePhoto = obx.QueryBooleanProperty<PhotoEntity>(
    _entities[4].properties[11],
  );

  /// See [PhotoEntity.displayOrder].
  static final displayOrder = obx.QueryIntegerProperty<PhotoEntity>(
    _entities[4].properties[12],
  );
}

/// [PreferenceEntity] entity fields to define ObjectBox queries.
class PreferenceEntity_ {
  /// See [PreferenceEntity.id].
  static final id = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[5].properties[0],
  );

  /// See [PreferenceEntity.userId].
  static final userId = obx.QueryStringProperty<PreferenceEntity>(
    _entities[5].properties[1],
  );

  /// See [PreferenceEntity.minAge].
  static final minAge = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[5].properties[2],
  );

  /// See [PreferenceEntity.maxAge].
  static final maxAge = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[5].properties[3],
  );

  /// See [PreferenceEntity.maxDistance].
  static final maxDistance = obx.QueryIntegerProperty<PreferenceEntity>(
    _entities[5].properties[4],
  );

  /// See [PreferenceEntity.genderPreferenceJson].
  static final genderPreferenceJson = obx.QueryStringProperty<PreferenceEntity>(
    _entities[5].properties[5],
  );

  /// See [PreferenceEntity.showOnlyVerified].
  static final showOnlyVerified = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[5].properties[6],
  );

  /// See [PreferenceEntity.showOnlyWithPhotos].
  static final showOnlyWithPhotos = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[5].properties[7],
  );

  /// See [PreferenceEntity.notifyMatches].
  static final notifyMatches = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[5].properties[8],
  );

  /// See [PreferenceEntity.notifyMessages].
  static final notifyMessages = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[5].properties[9],
  );

  /// See [PreferenceEntity.notifyLikes].
  static final notifyLikes = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[5].properties[10],
  );

  /// See [PreferenceEntity.showOnline].
  static final showOnline = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[5].properties[11],
  );

  /// See [PreferenceEntity.showDistance].
  static final showDistance = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[5].properties[12],
  );

  /// See [PreferenceEntity.incognitoMode].
  static final incognitoMode = obx.QueryBooleanProperty<PreferenceEntity>(
    _entities[5].properties[13],
  );

  /// See [PreferenceEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<PreferenceEntity>(
    _entities[5].properties[14],
  );

  /// See [PreferenceEntity.genderPreference].
  static final genderPreference =
      obx.QueryStringVectorProperty<PreferenceEntity>(
        _entities[5].properties[15],
      );
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// See [UserEntity.id].
  static final id = obx.QueryIntegerProperty<UserEntity>(
    _entities[6].properties[0],
  );

  /// See [UserEntity.userId].
  static final userId = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[1],
  );

  /// See [UserEntity.email].
  static final email = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[2],
  );

  /// See [UserEntity.fullName].
  static final fullName = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[3],
  );

  /// See [UserEntity.dateOfBirth].
  static final dateOfBirth = obx.QueryDateProperty<UserEntity>(
    _entities[6].properties[4],
  );

  /// See [UserEntity.gender].
  static final gender = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[5],
  );

  /// See [UserEntity.lookingFor].
  static final lookingFor = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[6],
  );

  /// See [UserEntity.bio].
  static final bio = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[7],
  );

  /// See [UserEntity.photosJson].
  static final photosJson = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[8],
  );

  /// See [UserEntity.photoUrl].
  static final photoUrl = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[9],
  );

  /// See [UserEntity.coverUrl].
  static final coverUrl = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[10],
  );

  /// See [UserEntity.profileCompleted].
  static final profileCompleted = obx.QueryBooleanProperty<UserEntity>(
    _entities[6].properties[11],
  );

  /// See [UserEntity.completionPercentage].
  static final completionPercentage = obx.QueryIntegerProperty<UserEntity>(
    _entities[6].properties[12],
  );

  /// See [UserEntity.occupation].
  static final occupation = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[13],
  );

  /// See [UserEntity.interestsJson].
  static final interestsJson = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[14],
  );

  /// See [UserEntity.heightCm].
  static final heightCm = obx.QueryIntegerProperty<UserEntity>(
    _entities[6].properties[15],
  );

  /// See [UserEntity.education].
  static final education = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[16],
  );

  /// See [UserEntity.relationshipStatus].
  static final relationshipStatus = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[17],
  );

  /// See [UserEntity.instagramHandle].
  static final instagramHandle = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[18],
  );

  /// See [UserEntity.spotifyAnthem].
  static final spotifyAnthem = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[19],
  );

  /// See [UserEntity.city].
  static final city = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[20],
  );

  /// See [UserEntity.country].
  static final country = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[21],
  );

  /// See [UserEntity.latitude].
  static final latitude = obx.QueryDoubleProperty<UserEntity>(
    _entities[6].properties[22],
  );

  /// See [UserEntity.longitude].
  static final longitude = obx.QueryDoubleProperty<UserEntity>(
    _entities[6].properties[23],
  );

  /// See [UserEntity.role].
  static final role = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[24],
  );

  /// See [UserEntity.lastActiveAt].
  static final lastActiveAt = obx.QueryDateProperty<UserEntity>(
    _entities[6].properties[25],
  );

  /// See [UserEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<UserEntity>(
    _entities[6].properties[26],
  );

  /// See [UserEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<UserEntity>(
    _entities[6].properties[27],
  );

  /// See [UserEntity.accessToken].
  static final accessToken = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[28],
  );

  /// See [UserEntity.refreshToken].
  static final refreshToken = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[29],
  );

  /// See [UserEntity.tokenExpiresAt].
  static final tokenExpiresAt = obx.QueryDateProperty<UserEntity>(
    _entities[6].properties[30],
  );

  /// See [UserEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<UserEntity>(
    _entities[6].properties[31],
  );

  /// See [UserEntity.pendingActionsJson].
  static final pendingActionsJson = obx.QueryStringProperty<UserEntity>(
    _entities[6].properties[32],
  );

  /// See [UserEntity.photos].
  static final photos = obx.QueryStringVectorProperty<UserEntity>(
    _entities[6].properties[33],
  );

  /// See [UserEntity.interests].
  static final interests = obx.QueryStringVectorProperty<UserEntity>(
    _entities[6].properties[34],
  );

  /// See [UserEntity.pendingActions].
  static final pendingActions = obx.QueryStringVectorProperty<UserEntity>(
    _entities[6].properties[35],
  );
}
